release:
  stage: deploy
  script:
    - ./gradlew assembleRelease
    - ./gradlew copyReleaseArtifact
    - mv ./*.apk ./SynoManager-${CI_BUILD_TAG}-release-${CI_BUILD_ID}.apk
  only:
    - tags
  artifacts:
    name: "SynoManager_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    paths:
        - ./*.apk
